driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: freebsd-10.3
- name: freebsd-11.0

suites:
- name: portsnap
  run_list: freebsd::portsnap

- name: pkgng
  run_list: freebsd::pkgng
