driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: freebsd-10
- name: freebsd-11

suites:
- name: portsnap
  run_list: 
    - recipe[freebsd::portsnap]
    - recipe[test::default]

- name: pkgng
  run_list: 
    - recipe[freebsd::pkgng]
    - recipe[test::default]
